from src_machine_learning.estrategia_modelo.estrategia_modelo_svr import EstrategiaModeloSVR
from src_machine_learning.processador.prepocessador_sklearn import PrepocessadorSklearnn

p = PrepocessadorSklearnn[EstrategiaModeloSVR]()
